- name: ps-docs
  uses: microsoft/ps-docs@v0.1.0
  with:
    # The path PSDocs will look for files to input files.
    inputPath: # optional, default is 
    # A comma separated list of modules to use containing document definitions.
    modules: # optional, default is 
    # An path containing definitions to use for generating documentation.
    source: # optional, default is .ps-docs/
    # A comma separated list of conventions to use for generating documentation.
    conventions: # optional, default is 
    # The path to write documentation to.
    outputPath: # optional, default is 
    # The working directory PSDocs is run from.
    path: # optional, default is 
    # Determine if a pre-release module version is installed.
    prerelease: # optional, default is false
